# Generated by Django 5.1.3 on 2025-04-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('presentation', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('distributor', models.CharField(max_length=100)),
                ('composition', models.TextField(blank=True)),
                ('family', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('atc_code', models.CharField(max_length=15)),
                ('public_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospital_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('table', models.CharField(max_length=1)),
                ('indication', models.TextField()),
            ],
        ),
    ]
