# Generated by Django 5.1.3 on 2025-03-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.IntegerField()),
                ('unity', models.CharField(max_length=50)),
                ('manufacturer', models.TextField()),
                ('composition', models.TextField()),
                ('therapeutic_class', models.TextField()),
                ('atc', models.CharField(max_length=20)),
                ('public_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospital_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indications', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
