# Generated by Django 5.1.3 on 2025-03-31 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='physician_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='physician',
            field=models.ManyToManyField(related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
