# Generated by Django 5.1.3 on 2025-03-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_physician_id_patient_physician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='physician',
            new_name='physicians',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
